### ISSUE TITLE
Your URL didn't respond with the value of the `challenge` parameter

### ISSUE THREAD

**Issue by plflanagan** [msolomonTMG/jira-comment-slack-notification#21]
I believe I have followed all the directions accurately, but on Step 6 I am getting the following error:

<img width="741" alt="screen shot 2019-01-09 at 5 21 50 pm" src="https://user-images.githubusercontent.com/9424428/50939797-26e5e900-1433-11e9-98eb-a97fa2692bb4.png">

Checking the logs of the heroku app, I see:
`at=error code=H10 desc="App crashed" method=GET path="/rest/applinks/1.0/manifest" host=app-name.herokuapp.com request_id=idNumber fwd="ip address" dyno= connect= service= status=503 bytes= protocol=https`

After researching this some, it seemed like a potential fix would be to restart the heroku app. This did not seem to be successful, however. Here was the output:
```
2019-01-10T01:27:21.417918+00:00 heroku[web.1]: State changed from crashed to starting
2019-01-10T01:27:21.156846+00:00 app[web.1]: Warning: connect.session() MemoryStore is not
2019-01-10T01:27:21.156876+00:00 app[web.1]: designed for a production environment, as it will leak
2019-01-10T01:27:21.156878+00:00 app[web.1]: memory, and will not scale past a single process.
2019-01-10T01:27:21.182713+00:00 app[web.1]: (node:4) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/4.x/docs/connections.html#use-mongo-client
2019-01-10T01:27:21.187009+00:00 app[web.1]: Node app is running on port 56004
2019-01-10T01:27:21.244152+00:00 app[web.1]: Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
2019-01-10T01:27:21.275384+00:00 app[web.1]: Succeeded connected to: mongodb://heroku_tjdkn20t:l303hirrfb1clvvlo30r28rqev@ds153394.mlab.com:53394/heroku_tjdkn20t
2019-01-10T01:27:21.320232+00:00 app[web.1]: /app/node_modules/vow/lib/vow.js:105
2019-01-10T01:27:21.320237+00:00 app[web.1]:             throw e;
2019-01-10T01:27:21.320239+00:00 app[web.1]:             ^
2019-01-10T01:27:21.320241+00:00 app[web.1]: 
2019-01-10T01:27:21.320242+00:00 app[web.1]: Error: missing_scope
2019-01-10T01:27:21.320244+00:00 app[web.1]:     at _api.then.fail (/app/node_modules/slackbots/index.js:42:33)
2019-01-10T01:27:21.320246+00:00 app[web.1]:     at Array.<anonymous> (/app/node_modules/vow/lib/vow.js:754:56)
2019-01-10T01:27:21.320248+00:00 app[web.1]:     at Immediate.callFns (/app/node_modules/vow/lib/vow.js:24:35)
2019-01-10T01:27:21.320249+00:00 app[web.1]:     at runCallback (timers.js:574:20)
2019-01-10T01:27:21.320251+00:00 app[web.1]:     at tryOnImmediate (timers.js:554:5)
2019-01-10T01:27:21.320253+00:00 app[web.1]:     at processImmediate [as _immediateCallback] (timers.js:533:5)
2019-01-10T01:27:21.395148+00:00 heroku[web.1]: Process exited with status 1
2019-01-10T01:27:24.996235+00:00 heroku[web.1]: Starting process with command `node app.js`
2019-01-10T01:27:28.815566+00:00 heroku[web.1]: State changed from starting to up
2019-01-10T01:27:28.920719+00:00 heroku[web.1]: State changed from up to crashed
2019-01-10T01:27:28.891636+00:00 heroku[web.1]: Process exited with status 1
2019-01-10T01:27:28.647943+00:00 app[web.1]: Warning: connect.session() MemoryStore is not
2019-01-10T01:27:28.648003+00:00 app[web.1]: designed for a production environment, as it will leak
2019-01-10T01:27:28.648005+00:00 app[web.1]: memory, and will not scale past a single process.
2019-01-10T01:27:28.668489+00:00 app[web.1]: (node:4) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/4.x/docs/connections.html#use-mongo-client
2019-01-10T01:27:28.675923+00:00 app[web.1]: Node app is running on port 55797
2019-01-10T01:27:28.745939+00:00 app[web.1]: Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
2019-01-10T01:27:28.772922+00:00 app[web.1]: Succeeded connected to: mongodb://heroku_tjdkn20t:l303hirrfb1clvvlo30r28rqev@ds153394.mlab.com:53394/heroku_tjdkn20t
2019-01-10T01:27:28.809627+00:00 app[web.1]: /app/node_modules/vow/lib/vow.js:105
2019-01-10T01:27:28.809646+00:00 app[web.1]:             throw e;
2019-01-10T01:27:28.809660+00:00 app[web.1]:             ^
2019-01-10T01:27:28.809661+00:00 app[web.1]: 
2019-01-10T01:27:28.809662+00:00 app[web.1]: Error: missing_scope
2019-01-10T01:27:28.809667+00:00 app[web.1]:     at _api.then.fail (/app/node_modules/slackbots/index.js:42:33)
2019-01-10T01:27:28.809668+00:00 app[web.1]:     at Array.<anonymous> (/app/node_modules/vow/lib/vow.js:754:56)
2019-01-10T01:27:28.809669+00:00 app[web.1]:     at Immediate.callFns (/app/node_modules/vow/lib/vow.js:24:35)
2019-01-10T01:27:28.809671+00:00 app[web.1]:     at runCallback (timers.js:574:20)
2019-01-10T01:27:28.809672+00:00 app[web.1]:     at tryOnImmediate (timers.js:554:5)
2019-01-10T01:27:28.809673+00:00 app[web.1]:     at processImmediate [as _immediateCallback] (timers.js:533:5)
```

Thoughts on how to fix this?

**Comment by thejmill** [comment]
Also, getting this error. 

Request URL Your URL didn't respond with the value of the challenge parameter.

**Comment by thejmill** [comment]
@plflanagan try Jira Integration+ works pretty well for notifying users when they are mentioned in comments.

**Comment by muchtall** [comment]
@plflanagan Just a friendly heads-up: You'll want to reset the credentials on your Heroko account. Looks like you accidentally posted them in the output above.
