### ISSUE TITLE
Internal Server Error on initial Heroku deploy

### ISSUE THREAD

**Issue by howlit** [msolomonTMG/jira-comment-slack-notification#24]
Going through the installation process and I can't get past the initial Heroku deployment. When I deploy the app and open the link it just says Internal Server Error. I checked all the configs and it seems to line up properly, but I continue to get that error message and can't get any further.

**Comment by Dock1100** [comment]
I have the same issue.
Here is a log from heroku app

```
2019-06-14T14:46:07.552530+00:00 app[web.1]: Error: Failed to lookup view "home" in views directory "/app/views"
2019-06-14T14:46:07.552551+00:00 app[web.1]: at EventEmitter.render (/app/node_modules/express/lib/application.js:580:17)
2019-06-14T14:46:07.552552+00:00 app[web.1]: at ServerResponse.render (/app/node_modules/express/lib/response.js:1008:7)
2019-06-14T14:46:07.552555+00:00 app[web.1]: at /app/app.js:155:9
2019-06-14T14:46:07.552556+00:00 app[web.1]: at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2019-06-14T14:46:07.552558+00:00 app[web.1]: at next (/app/node_modules/express/lib/router/route.js:137:13)
2019-06-14T14:46:07.552559+00:00 app[web.1]: at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
2019-06-14T14:46:07.552560+00:00 app[web.1]: at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2019-06-14T14:46:07.552562+00:00 app[web.1]: at /app/node_modules/express/lib/router/index.js:281:22
2019-06-14T14:46:07.552564+00:00 app[web.1]: at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
2019-06-14T14:46:07.552565+00:00 app[web.1]: at next (/app/node_modules/express/lib/router/index.js:275:10)
2019-06-14T14:46:07.552567+00:00 app[web.1]: at Immediate.<anonymous> (/app/node_modules/express-session/index.js:489:7)
2019-06-14T14:46:07.552568+00:00 app[web.1]: at runCallback (timers.js:578:20)
2019-06-14T14:46:07.552570+00:00 app[web.1]: at tryOnImmediate (timers.js:554:5)
2019-06-14T14:46:07.552571+00:00 app[web.1]: at processImmediate [as _immediateCallback] (timers.js:533:5)
```

**Comment by alexisboucharin** [comment]
I have the same problem with internal server error.
